theme: jekyll-theme-modernist

baseurl: /kb

collections_dir: collections

collections:
  howtos:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
