theme: jekyll-theme-slate
title: DIALS // knowledgebase
show_downloads: false

baseurl: /kb

collections_dir: collections

collections:
  howtos:
    output: true
    permalink: /:collection/:name
  meetings:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
